### ISSUE TITLE
failure to call connect callback

### ISSUE THREAD

**Issue by jeffmcaffer** [shyiko/amqplib-auto-recovery#1]
I have been trying to to use this library to open a confirm channel on Node 6.9.1 against RabbitMQ.  It seems that the invocation of my channel callback (#L86 in this library) is failing to run.  Stepping through with the debugger I get right to line 86 and step into but nothing happens.  I have a breakpoint at the first line of the callback and it does not get hit.  

Have you ever seen something like this?  Thoughts on what could be wrong?

**Comment by shyiko** [comment]
Hi @jeffmcaffer. 

I've just tried to put everything together:
- Node.js v6.9.1
- RabbitMQ 3.6.1 (`docker run -d -p 5672:5672 -p 15672:15672 --hostname rabbitmq --name rabbitmq rabbitmq:3.6.1-managemen`)
- amqplib@0.5.1 + amqplib-auto-recovery@0.1.0
- ...and the following script
```javascript
const amqp = require('amqplib/callback_api');
const withAutoRecovery = require('amqplib-auto-recovery');

withAutoRecovery(amqp, {
  onError: (err) => { console.log(err.message) },
}).connect("amqp://localhost", (err, con) => {
  if (err) {
    console.error(`Failed to connect (${err.message})`);
    return
  }
  console.info("Connection established");
  con.createConfirmChannel((err, ch) => {
    if (err) {
      console.error(`Failed to create a channel (${err.message})`);
      return
    }
    ch.assertQueue('q1', {durable: true});
    ch.sendToQueue('q1', new Buffer('message'), {},
      function(err) {
        if (err !== null) {
          console.warn('Message nacked!');
        } else {
          console.log('Message acked');
        }
      });
  });
});
```

Everything seems to be OK. No problems with debugger either (WebStorm 2016.3). I might be able to help if you provide more details (maybe a sample project?).

**Comment by shyiko** [comment]
Closing due to the lack of response. Feel free to reopen.
